name: Tests

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.11']
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install -U -r requirements_dev.txt
        pip install -U -r requirements_backend.txt
        pip install -U -e .[cssselect,pyquery]
    
    - name: Instrument code
      uses: AryazE/auto-dylin/instrument@main
      with:
        analysis-coverage: false

    - name: Start MongoDB
      uses: ankane/setup-mongodb@v1
      #uses: supercharge/mongodb-github-action@1.8.0 # does not work on macos
      #with:
      #  mongodb-version: 5.0

    - name: Start Redis
      if: runner.os == 'Linux'
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 5

    - name: Run tests
      shell: bash
      run: |
        pytest -n 4 --timeout 300
    
    - name: DyLin reports
      if: always()
      uses: AryazE/auto-dylin/report@main
